### ISSUE TITLE
Merge Dynamic Inputs from MEM into CTM output

### ISSUE THREAD

**Issue by HolmquistJ** [tilbud/rCTM#2]
Correct me if I'm wrong, but overall, full-blown MEM should spin up at steady state for a certain about of time generate n cohorts. Then once that initial condition is met, we begin a new module in which belowground biomass and surface inorganic sediment input are dynamic responses to sea-level rise.

@ktoddbrown I know you're working on this with the CTM v 5. We'll need to retool things when I get CTM 6 working.

**Comment by ktoddbrown** [comment]
I'm closing super stale issues :) Will start a new one on modifications needed for full blown MEM
