### ISSUE TITLE
Model Documentation

### ISSUE THREAD

**Issue by HolmquistJ** [tilbud/rCTM#3]
It would be great to have a readMe.md or readMe.pdf in the main body of the repo.
*  Should include basic equations, figures, and diagrams which show how CTM, MEM, and full-blown MEM work and work together.
*  Should also include summaries and citations of Jim's previous papers.
*  It would also be great to have a table that lists the names, descriptions, and units for all the inputs and parameters in CTM/MEM. I know Andre and Sam are working on this for their CCRCN Soils WG January homework.

**Comment by ktoddbrown** [comment]
Closing this and breaking down some of these tasks into bite sized issues.
